-- Active: 1774679762050@@127.0.0.1@3306@dev_portfolio_builder
CREATE TABLE IF NOT EXISTS users (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	username VARCHAR(40) NOT NULL UNIQUE,
	full_name VARCHAR(120) NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS portfolios (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INT UNSIGNED NOT NULL UNIQUE,
	public_slug VARCHAR(40) NOT NULL UNIQUE,
	full_name VARCHAR(120) NOT NULL,
	headline VARCHAR(160) NOT NULL,
	location VARCHAR(120) NOT NULL,
	experience_summary VARCHAR(160) NOT NULL,
	education VARCHAR(160) NOT NULL,
	availability VARCHAR(255) NOT NULL,
	phone VARCHAR(60) NOT NULL DEFAULT '',
	avatar_url TEXT NOT NULL,
	cover_url TEXT NOT NULL,
	github_url VARCHAR(255) NOT NULL DEFAULT '',
	github_username VARCHAR(100) NOT NULL DEFAULT '',
	linkedin_url VARCHAR(255) NOT NULL DEFAULT '',
	header_actions_json JSON NULL,
	about_json JSON NOT NULL,
	timeline_json JSON NOT NULL,
	experiences_json JSON NOT NULL,
	tech_categories_json JSON NOT NULL,
	projects_json JSON NOT NULL,
	custom_sections_json JSON NOT NULL,
	layout_json JSON NULL,
	chat_enabled TINYINT(1) NOT NULL DEFAULT 1,
	gemini_api_key VARCHAR(255) NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT fk_portfolios_user
		FOREIGN KEY (user_id) REFERENCES users(id)
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS portfolio_versions (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INT UNSIGNED NOT NULL,
	name VARCHAR(120) NOT NULL,
	is_active TINYINT(1) NOT NULL DEFAULT 0,
	snapshot_json JSON NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	INDEX idx_portfolio_versions_user (user_id),
	CONSTRAINT fk_portfolio_versions_user
		FOREIGN KEY (user_id) REFERENCES users(id)
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS resumes (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INT UNSIGNED NOT NULL UNIQUE,
	template_key VARCHAR(60) NOT NULL DEFAULT 'deux_modern_v1',
	content_json JSON NOT NULL,
	layout_json JSON NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT fk_resumes_user
		FOREIGN KEY (user_id) REFERENCES users(id)
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS resume_versions (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INT UNSIGNED NOT NULL,
	name VARCHAR(120) NOT NULL,
	is_active TINYINT(1) NOT NULL DEFAULT 0,
	snapshot_json JSON NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	INDEX idx_resume_versions_user (user_id),
	CONSTRAINT fk_resume_versions_user
		FOREIGN KEY (user_id) REFERENCES users(id)
		ON DELETE CASCADE
);
